### ISSUE TITLE
Support insert all with already gzipped data

### ISSUE THREAD

**Issue by idobenamram** [lquerel/gcp-bigquery-client#108]
In our system we want to limit our inserts to a certain bandwidth. to do this we need to serialise and compress our data twice, once to calculate the bandwidth we take, and another time in your `insert_all` function. it would be great if you can add an endpoint which receives the compressed request already. another option is making `TableDataInsertAllRequest` struct smarter by keeping the compressed data which we can check the length of before we send. thank you!

**Comment by idobenamram** [comment]
i can write the pr myself, but i would like to know which option fits better with your design (and that you like more)

**Comment by lquerel** [comment]
Sorry for the delay in my response. I think the option of having a dedicated endpoint is the best. Could you submit a PR to that effect? Thanks.

**Comment by idobenamram** [comment]
i don't have premissions to open a new branch for the pull request, do u want me to open it from a fork?

**Comment by lquerel** [comment]
Available in version 0.24.1. Thanks
