### ISSUE TITLE
Replace chrono dependency with time?

### ISSUE THREAD

**Issue by birdsarah** [lquerel/gcp-bigquery-client#17]
result of cargo audit when trying to use gcp-bigquery-client:

```
Crate:         chrono
Version:       0.4.19
Title:         Potential segfault in `localtime_r` invocations
Date:          2020-11-10
ID:            RUSTSEC-2020-0159
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution:      No safe upgrade is available!
Dependency tree: 
chrono 0.4.19
├── yup-oauth2 6.3.1
│   └── gcp-bigquery-client 0.11.0
│       └── cjms 1.0.0
└── gcp-bigquery-client 0.11.0
```

chrono does not appear to be actively maintained.

Could the `time` crate meet the needs of this repo?

I have recently had a PR merged into yup-oauth2 that moves that crate from chrono to time. https://github.com/dermesser/yup-oauth2/pull/172 **I'd be happy to do a PR here too**. 

This would have helped me with integrating gcp-bigquery-client into my project. In the end I've needed such a small fraction of the power of your repo that I've just taken the [few pieces that I need](https://github.com/mozilla-services/cjms/pull/30/files#diff-731d97cf752436d68f1591d2e93068c772080c9bf9d5bc3cf533297bdd39c264R1).

**Comment by lquerel** [comment]
Version 0.12.0 published. I replaced Chrono with Time and changed the version of Yup-Oauth2 to a version not using Chrono as well. There is still an indirect dependency to Chrono via CloudStorage crate only used in an example. So I put a feature on the example and made CloudStorage an optional dependency. Hope that will be enough on your side.
