### ISSUE TITLE
Allow to change the base url

### ISSUE THREAD

**Issue by MarcoIeni** [lquerel/gcp-bigquery-client#36]
Hi! I would like to test this crate locally by using [bigquery-emulator](https://github.com/goccy/bigquery-emulator).
However, this crate doesn't allow changing the base url (it always assumes `https://bigquery.googleapis.com/bigquery/v2/`):
https://github.com/lquerel/gcp-bigquery-client/blob/51f1acb4cfa8885919936e5e9ecd283fa64739e5/src/project.rs#L46

Instead, `google_bigquery2` allows to customize both the [base_url](https://docs.rs/google-bigquery2/4.0.1+20220222/google_bigquery2/api/struct.Bigquery.html#method.base_url) and the [root_url](https://docs.rs/google-bigquery2/4.0.1+20220222/google_bigquery2/api/struct.Bigquery.html#method.root_url).

Do you plan to add support for this?
If not, would you accept a PR?
Thanks 🙏

**Comment by lquerel** [comment]
Merged and published. Thanks
