### ISSUE TITLE
Let `Client::from_service_account_key_file` return `Result<Client, BQError>`

### ISSUE THREAD

**Issue by burmecia** [lquerel/gcp-bigquery-client#39]
The function `Client::from_service_account_key_file` is easy to fail by common errors, such as wrong file path, invalid key file, have no permission and etc.  Any particular reason why it doesn't return `Result<Client, BQError>` like `Client::from_service_account_key`?

**Comment by lquerel** [comment]
Definitely something that should be improved. Contributions are welcome.
