### ISSUE TITLE
Support BigQuery Storage API

### ISSUE THREAD

**Issue by unvalley** [lquerel/gcp-bigquery-client#53]
I'd like to use [BigQuery Storage API](https://cloud.google.com/bigquery/docs/reference/storage/libraries) through this crate.
And this should be planned, so I created this issue.

> Yes, covering all the capabilities of BQ is the goal, even if many things are still missing (e.g. the storage read/write API). https://github.com/lquerel/gcp-bigquery-client/discussions/11#discussioncomment-1536006

**Comment by lquerel** [comment]
Yes I agree. I have a draft implementation of the storage write API in a private repo. I need to find time to port that into this public repo and clean it. That represents a lot of work, I don't know yet when I will be able to do that.

**Comment by unvalley** [comment]
@lquerel Thank you for your work. I'm looking forward to merging that!

**Comment by lazareviczoran** [comment]
Hello! Any updates on this? Is there any way we can help to get this implemented?

**Comment by imor** [comment]
I have opened a draft PR to add support for the AppendRows api in #95. @lquerel If this looks ok, it can be merged and other APIs can be added later slowly. Alternatively, if this PR doesn't look good, could you please make your private repo code available for me to take a look. I can help in cleaning it up and merging it in this repo.
