### ISSUE TITLE
"Rows are not present" panics for query_all

### ISSUE THREAD

**Issue by blombern** [lquerel/gcp-bigquery-client#61]
I've been using version `0.16.6` since it's release, paging through big results with occasional panics but successfully. Since a few days ago my ingestion panics on every request, making it unusable. I'm wondering if there's been a change on Google's end?

I'm now running on `0.16.7` and the only way i could get some successful queries going was to cut my query size way way down. But this is multiplying my query cost and still panicking quite often.

**Comment by blombern** [comment]
I managed to resolve the issue by increasing the default timeout in `GetQueryResultsParameters` for `query_all`. Could the timeout be passed in as a parameter to the function? Happy to contribute a PR.

**Comment by magnalite** [comment]
Related, #54 appears to fix this for `query_all_with_location` but not `query_all`.
